remote_theme: pages-themes/midnight@v0.2.0   # https://github.com/pages-themes/midnight/tree/master
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dave Pinkawa's Blog
tagline: Leadership, Smoking Meat, and Leveling Up Life — Balancing Family, Fires, and Fun
description: A light-hearted blog sharing insights on family life, smoking meat recipes, and video game adventures.

